### ISSUE TITLE
Syntax highlighting in Readme

### ISSUE THREAD

**Issue by geopic** [Livshitz/di.libx.js#1]
Hey, I saw your project on Reddit and was interested in checking it out. I notice your code examples in the Readme don't have colours like you'd find in an IDE. If you want I can make a small contribution to the project by adding syntax highlighting to the code in the Readme so it can be read and understood easier.

**Comment by Livshitz** [comment]
That'd be great, thanks @geopic! 🙏

**Comment by geopic** [comment]
Excellent, I'll start on it now.
