### ISSUE TITLE
Convert `var` to `const` or `let`

### ISSUE THREAD

**Issue by Livshitz** [Livshitz/di.libx.js#4]
Especially in:
[DependencyInjector.ts](https://github.com/Livshitz/di.libx.js/blob/master/src/DependencyInjector.ts)

**Comment by adambocco** [comment]
Hi,
I'm a senior CS student and am really interested in working on open source projects. This is my first issue and I would love to help with this.

**Comment by Livshitz** [comment]
@adambocco your help would be greatly appreciate 🙏
